const requests = [
  {
    id: 1,
    bloodType: "B+",
    name: "Honest Albert",
    age: 22,
    gender: "M",
    priority: "urgent",
    place: "Toyotasa Acil Yardım Hastanesi",
  },
  {
    id: 2,
    bloodType: "O-",
    name: "Mark Leevoy",
    age: 14,
    gender: "M",
    priority: "less urgent",
    place: "Yenikent Devlet Hastanesi",
  },
  {
    id: 3,
    bloodType: "B+",
    name: "Emmanuel Wilfred",
    age: 8,
    gender: "M",
    priority: "urgent",
    place: "Sakarya Üniversitesi Eğitim Ve Araştırma Hastanesi",
  },
  {
    id: 4,
    bloodType: "A+",
    name: "Ilaria Rosali",
    age: 12,
    gender: "F",
    priority: "non-urgent",
    place: "Hendek Devlet Hastanesi",
  },
  {
    id: 5,
    bloodType: "O-",
    name: "Abdulrahim Ferunzy",
    age: 66,
    gender: "M",
    priority: "very urgent",
    place: "Sakarya Üniversitesi Eğitim Ve Araştırma Hastanesi",
  },
  {
    id: 6,
    bloodType: "A+",
    name: "Donaldo Omondi",
    age: 33,
    gender: "M",
    priority: "urgent",
    place: "Akyazı Devlet Hastanesi",
  },
  {
    id: 7,
    bloodType: "A+",
    name: "Ayşe Öztürk",
    age: 42,
    gender: "Female",
    priority: "Urgent",
    place: "Sakarya Devlet Hastanesi",
  },
  {
    id: 8,
    bloodType: "O-",
    name: "Mustafa Arslan",
    age: 28,
    gender: "Male",
    priority: "Very Urgent",
    place: "Sakarya Üniversitesi Hastanesi",
  },
  {
    id: 9,
    bloodType: "B+",
    name: "Fatma Yıldız",
    age: 56,
    gender: "Female",
    priority: "Less Urgent",
    place: "Sakarya Özel Hastanesi",
  },
  {
    id: 10,
    bloodType: "AB-",
    name: "Mehmet Kaya",
    age: 39,
    gender: "Male",
    priority: "Urgent",
    place: "Sakarya Eğitim ve Araştırma Hastanesi",
  },
  {
    id: 11,
    bloodType: "O+",
    name: "Zeynep Çelik",
    age: 24,
    gender: "Female",
    priority: "Very Urgent",
    place: "Sakarya Devlet Hastanesi",
  },
  {
    id: 12,
    bloodType: "A-",
    name: "Ahmet Demir",
    age: 51,
    gender: "Male",
    priority: "Less Urgent",
    place: "Sakarya Üniversitesi Hastanesi",
  },
  {
    id: 13,
    bloodType: "B-",
    name: "Selin Akgün",
    age: 34,
    gender: "Female",
    priority: "Urgent",
    place: "Sakarya Özel Hastanesi",
  },
  {
    id: 14,
    bloodType: "AB+",
    name: "Ali Şahin",
    age: 47,
    gender: "Male",
    priority: "Very Urgent",
    place: "Sakarya Eğitim ve Araştırma Hastanesi",
  },
  {
    id: 15,
    bloodType: "O-",
    name: "Aylin Demir",
    age: 31,
    gender: "Female",
    priority: "Less Urgent",
    place: "Sakarya Devlet Hastanesi",
  },
  {
    id: 16,
    bloodType: "B+",
    name: "Emin Arslan",
    age: 43,
    gender: "Male",
    priority: "Urgent",
    place: "Sakarya Üniversitesi Hastanesi",
  },
];

const chart = [
  1.1, 3, 1.5, 2.3, 3.2, 7, 8.2, 1.2, 2, 1.2, 8, 3.8, 5.8, 3.9, 5.1, 0.1, 6,
];

const user = {
  avatar: require("../../../../assets/image/ProfilePhoto.png"),
};

const locations = [{ latitude: 37.78825, longitude: -122.4324 }];

export { requests, chart, user, locations };
